stages:
  great_expectations:
    cmd: | 
      python3 src/gx_validation.py --csv london_weather.csv
    deps:
      - data/london_weather.csv
      - src/gx_validation.py
    outs:
      - output/metrics.json

  train_model:
    cmd: |
      python3 src/train_model.py --csv old_london_weather.csv --params '{"model__max_depth": [5], "model__n_estimators": [100]}'
    deps:
      - data/london_weather.csv
      - src/train_model.py
    outs:
      - output/model_metrics.json
      - output/model.pkl

  monitor_model:
    cmd: |
      python3 src/monitor_model.py --date_col "date" --y_label "mean_temp" --method "wasserstein" --reference_csv "old_london_weather.csv" --analysis_csv "new_london_weather.csv"
    deps:
      - data/old_london_weather.csv
      - data/new_london_weather.csv
      - output/model.pkl
      - src/monitor_model.py
    outs:
      - output/multivariate.png
      - output/results_multivariate.csv
      - output/univariate.png
      - output/results_univariate.csv
      - output/performance.png
      - output/performance_results.csv
      - output/feature_drift_ranker.csv
      - output/feature_drift_correlation_ranker.csv