# This is a basic workflow to help you get started with Actions

name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
    contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Requirements
        run: |
          pip install -r requirements.txt

      - name: DVC
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git rm -r --cached 'output/metrics.json'
          git commit -m "stop tracking output/metrics.json"
          dvc repro
          # dvc commit
          # dvc push

      - name: Git Update
        run: |
          ls output/
          # last_commit=$(git log --format="%H" -n 1)
          # git config user.name github-actions
          # git config user.email github-actions@github.com
          # git config set advice.addIgnoredFile false
          # git add output/metrics.json
          # git commit -m "refresh files that were generated in commit $last_commit"
          # git push

