# This is a basic workflow to help you get started with Actions

name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "pr-validation" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
    contents: write
    pull-requests: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Requirements
        run: |
          pip install -r src/requirements.txt

      - name: Empty Files
        run: |
          touch output/metrics.json
          touch output/model_metrics.json
          touch output/model.pkl

          # Commit here only if there was any changes
          if git diff --quiet; then
            echo "No changes to commit, skipping commit."
          else
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add -f output/
            git commit -m "empty files for dvc"
            git push
          fi
          
      - name: DVC
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git rm -r --cached output/
          git commit -m "stop tracking outputs"
          dvc repro
          dvc metrics diff --md > change.md
          dvc dag
          dvc dag --outs

      - name: Git Update
        run: |
          last_commit=$(git log --format="%H" -n 1)
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -f output/ .dvc/cache dvc.lock
          git commit -m "refresh files that were generated in commit $last_commit"
          git push

      - uses: iterative/setup-cml@v1

      - name: Metrics Validation
        run: |
          dvc metrics show --md > report.md
          cml comment create report.md
          cml comment create change.md

          result1=$(cat change.md)
          result2=$(cat change.md | cut -d '|' -f 18)
          result3=$(cat change.md | cut -d '|' -f 6)
          result4=$(cat change.md | cut -d '|' -f 6 | tail -1)

          echo $result1
          echo $result2
          echo $result3
          echo $result4

          echo "teste"
          
          if echo "$(cat change.md | tail -n +2 | cut -d '|' -f 6 | tail -1)" | awk '{if ($1 > -10) print "true"; else print "false"}' | grep -q "true"; then
              cml pr create --message "Hyperparameter" --branch "pr-validation" --target-branch "main"
          else
              echo "Condition to open a Pull Request not satisfied"
          fi

        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN  }}

