name: PR

on:
  pull_request:
    branches: [ "main" ]

permissions:
   pull-requests: write

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
          message: |
            New PR! :wave:
        
      - name: Requirements
        run: |
          pip install black

      - name: black validation
        run: |
          python -m black --check .
