name: PR

on:
  pull_request:
    branches: [ "main" ]

env:
  files: |
    - src/train_model.py
    - src/monitor_model.py
    - src/gx_validation.py

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Requirements
        run: |
          pip install black

      - name: black validation
        run: |
          echo "Files to be tracked: {{  env.files  }}"
          python -m black --check {{  env.files }}
          # if [ $? -eq 0 ]; then
          #     exit 0
          # else
          #     exit 1
          # fi
